# 世界五百强公司有哪些

match

 $1 isa entitytype-entity, has name "世界五百强";
 $2 isa entitytype-entity, has name $3;
 $4 (company-corptype:$1,corptype-company:$2) isa company-corp-type;
 get $3; count;


 # 某个公司是不是世界五百强
 match
  $1 isa entitytype-entity, has name "世界五百强";
  $2 isa entitytype-entity, has name "百度";
  $4 (company-corptype:$1,corptype-company:$2) isa company-corp-type;
  get $3; count;


match $1 isa entitytype-entity, has name "沃尔玛2";


match $1 isa school-type-entity, has name "211";get;

match $0 isa school-type-entity, has name $1;get;

# 通过id直接match
match $x id V194629800; get;

# compute
compute count in school-type-entity;

compute count in entity-type-entity;

# xx公司 - xx集团 （直接）
compute path from V42463416, to V34730192;

# keyword - 公司 - 公司类型 （间接） keywords-of-corptype
compute path from V107503784, to V7118992;

match
$k isa entitytype-entity, has name "速卖通";
$ct isa entitytype-entity, has name "bat";
(corptype-keyword: $k, keyword-corptype: $ct) isa keywords-of-corptype-rule;
get $c;
